const commentData = [{"commentBody":"ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo"},
{"commentBody":"diam in magna bibendum imperdiet nullam orci pede venenatis non sodales"},
{"commentBody":"dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio"},
{"commentBody":"lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut"},
{"commentBody":"lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec"},
{"commentBody":"odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit"},
{"commentBody":"suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum"},
{"commentBody":"velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros"},
{"commentBody":"maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices"},
{"commentBody":"quis orci eget orci vehicula condimentum curabitur in libero ut"},
{"commentBody":"erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi"},
{"commentBody":"quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac"},
{"commentBody":"massa volutpat convallis morbi odio odio elementum eu interdum eu"},
{"commentBody":"convallis nulla neque libero convallis eget eleifend luctus ultricies eu"},
{"commentBody":"ante vel ipsum praesent blandit lacinia erat vestibulum sed magna"},
{"commentBody":"orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus"},
{"commentBody":"placerat ante nulla justo aliquam quis turpis eget elit sodales"},
{"commentBody":"mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea"},
{"commentBody":"tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque"},
{"commentBody":"sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus"},
{"commentBody":"nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac"},
{"commentBody":"mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed"},
{"commentBody":"in porttitor pede justo eu massa donec dapibus duis at"},
{"commentBody":"at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac"},
{"commentBody":"erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam"},
{"commentBody":"dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula"},
{"commentBody":"hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris"},
{"commentBody":"tempus vivamus in felis eu sapien cursus vestibulum proin eu mi"},
{"commentBody":"purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient"},
{"commentBody":"dui proin leo odio porttitor id consequat in consequat ut"},
{"commentBody":"tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in"},
{"commentBody":"velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla"},
{"commentBody":"eget rutrum at lorem integer tincidunt ante vel ipsum praesent"},
{"commentBody":"ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci"},
{"commentBody":"ut suscipit a feugiat et eros vestibulum ac est lacinia"},
{"commentBody":"accumsan felis ut at dolor quis odio consequat varius integer"},
{"commentBody":"aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet"},
{"commentBody":"tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc"},
{"commentBody":"sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi"},
{"commentBody":"rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed"},
{"commentBody":"curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi"},
{"commentBody":"fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer"},
{"commentBody":"adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc"},
{"commentBody":"vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia"},
{"commentBody":"duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum"},
{"commentBody":"mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient"},
{"commentBody":"felis ut at dolor quis odio consequat varius integer ac leo"},
{"commentBody":"nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat"},
{"commentBody":"curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi"},
{"commentBody":"justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices"}];

module.exports = commentData;